### ISSUE TITLE
doesn't work for identification (_id) counting

### ISSUE THREAD

**Issue by nasr18** [typegoose/auto-increment#1]
we are using separate collection `identitycounters` to store auto-incremented value along with other collections name to avoid using duplicate incremented count for other records.

**Comment by hasezoey** [comment]
thanks, should have checked that one, but forgot

should be fixed with 0.1.2

**Comment by hasezoey** [comment]
sorry thought this was an different issue - my bad

**Comment by hasezoey** [comment]
to the actual issue: why do you need an separate collection to keep track of the counter? i saw the other plugin do this - but i didnt(and still dont) understand why

**Comment by nasr18** [comment]
@hasezoey what if we delete any record, say if we delete a record which id equals 7 and at the same time if we insert a new doc?

**Comment by hasezoey** [comment]
@nasr18 oh, you use it for identification - sorry, yes will add this later

**Comment by nasr18** [comment]
@hasezoey I'm re-writing your plugin in the way of `mongoose-auto-increment`. `getModelForClass(counterClass)` returns nothing. If i find a solution for this means, I'll surely get what I want.

**Comment by nasr18** [comment]
@hasezoey any update on this?

**Comment by hasezoey** [comment]
@nasr18 not really, because i was "waiting" for you to push some sort of pull request / make some suggestions, and otherwise was busy with some other project

**Comment by hasezoey** [comment]
@nasr18 is 0.2.0 more what you asked for? (dd1da82bd3e6aeb8b187a7b4eeb4169a85396ebd)

**Comment by hasezoey** [comment]
i guess thanks to 0.2.0 and #2, this issue can be closed
