### ISSUE TITLE
Add `modelName` option API

### ISSUE THREAD

**Issue by surmon-china** [typegoose/auto-increment#11]
https://github.com/typegoose/auto-increment/blob/e28098f009e7e59a8e93ba385db15a0faa81514f/src/autoIncrement.ts#L124

The `modelName` key field is important, Its change will cause the auto-increment to restart from 0, so it is already an option that can be controlled by the user.

**Comment by hasezoey** [comment]
i dont quite understand your question, please update to be more clear on what you are asking

if you are asking to change the `modelName` because of a model name re-name, you should manually update the tracker document in the tracker collection (at least for now)
