### ISSUE TITLE
Support mongoose v6.1.x

### ISSUE THREAD

**Issue by AliYusuf95** [typegoose/auto-increment#12]
## What is the Problem?

Should support mongoose v6.1.x,
current peer dependency is `mongoose@~6.0.7`

**Comment by hasezoey** [comment]
no problem, just forgot to update this plugin - will do today, if i dont forget

**Comment by hasezoey** [comment]
Fixed with:
- 9d66a5c045bbe7cdaea6bbd20900210e69c163b8
- 8e90d7bf9091798360ee603ae5c0be7eef978569

released in version [`1.1.0`](https://github.com/typegoose/auto-increment/releases/tag/v1.1.0)
