### ISSUE TITLE
Mongoose 7+ compatibility

### ISSUE THREAD

**Issue by MajorTanya** [typegoose/auto-increment#19]
## Describe what you need

Hello, I'd like to use this package as a replacement for mongoose-sequence, which breaks with the newest Mongoose version 7.
This package's peerDependency conflicts with Mongoose 7 though, as it is only “~6.10.0” which isn't compatible with the new Mongoose version.

Considering Mongoose 7 dropped callback support in many places, this may not be feasible, but I'd be happy to hear from you regarding this issue.

## Do you have already an idea for the implementation?

*no*

**Comment by hasezoey** [comment]
this plugin does not use callbacks since its creation, i had originally waited to update this plugin when typegoose's next major is released

when not using types, you could also just overwrite the mongoose dependency used and it *should work*, though i will update it soon
