### ISSUE TITLE
it doesnot work on bulk insert like insert many

### ISSUE THREAD

**Issue by Ashish492** [typegoose/auto-increment#20]
## Versions

- auto-increment: 0.0.0
- mongoose: 0.0.0

**Comment by hasezoey** [comment]
please fill out more of your question.

---

also note that this plugin is currently set-up to only work on `save` hooks (for both `AutoIncrementID` and `AutoIncrementSimple`)

**Comment by Ashish492** [comment]
could i make for bulk insert

**Comment by hasezoey** [comment]
for `AutoIncrementSimple` it could probably be done, but i dont know about `AutoIncrementID` (without using transactions or multiple queries that are non-atomic)
