### ISSUE TITLE
Update mongoose to a safe version (latest 7.5.0 should work fine)

### ISSUE THREAD

**Issue by EpicUsername12** [typegoose/auto-increment#22]
Vulnerability in mongodb driver: https://github.com/advisories/GHSA-vxvm-qww3-2fh7

**Comment by hasezoey** [comment]
done with 1c4d5321b3131cc1e5430caecf8d7e09f1a9aaf7

Released in [3.5.0](https://github.com/typegoose/auto-increment/releases/tag/v3.5.0)
