### ISSUE TITLE
Convert _id from ObjectId to incremental number 

### ISSUE THREAD

**Issue by Luarb** [typegoose/auto-increment#5]
I read the docs and I wrote this code :

```ts
import { prop, plugin } from "@typegoose/typegoose";
import { AutoIncrementIDOptions, AutoIncrementID } from "@typegoose/auto-increment";

@plugin<AutoIncrementIDOptions>(AutoIncrementID, {})
export class BaseModel<T> {

    @prop()
    _id: number;

    @prop()
    name: string;

}
```
but it doesn't work the _id field is still an objectId not a auto incremented number.
Can you please tell me how can I implement this ?

**Comment by hasezoey** [comment]
could you provide how you interact with the model / how you create an doc?

**Comment by Luarb** [comment]
Correction, sorry I just tested  that this works if  I use the create method but it doesn't work with the insertMany :

```
    async insertMany(items: DocumentType<T>[] ): Promise<DocumentType<T>[]>  {
        return await this.model.insertMany(items);
    }
```

**Comment by hasezoey** [comment]
it only works if mongoose says it is an "new document" (i dont know how `insertMany` works internally)

**Comment by Luarb** [comment]
Would be cool if was add to the `insertMany`  but anyway great repo, started !
