### ISSUE TITLE
Not working with upsert?

### ISSUE THREAD

**Issue by wong2** [typegoose/auto-increment#8]
I have a model `User`: 

```ts
@plugin(AutoIncrementID, { field: 'uid' })
class User {
  @prop()
  uid: number
  ...
}
```

here is the code that find or create a user:

```ts
  const user = await User.findOneAndUpdate(
    { _id: userId },
    {
      $setOnInsert: {
        nickname,
      },
    },
    { upsert: true, new: true, setDefaultsOnInsert: true },
  ).exec()
```

and `uid` is not automatically added to the document.

After enabling debug log I can confirm that `schema.pre('save', ...` is not triggered.

And here is the document in `identitycounters`:

```json
{
    "_id" : ObjectId("5efadb0a23647200182d4c3d"),
    "count" : -1,
    "model" : "users",
    "field" : "uid",
    "__v" : 0
}
```

**Comment by hasezoey** [comment]
known issue, cannot be fixed (its and mongodb issue, defaults with upsert and any `$` parameter will not work)

**Comment by wong2** [comment]
Thanks for your quick reply! Is there any advice on an alternative implementation?

**Comment by hasezoey** [comment]
i can only think of one option: try to find the object you want, and if not there, create it, if there update it (`.find`, `.create`, modify & `.save`)

**Comment by wong2** [comment]
thanks
